name: deploy-auth
on:
  push:
    branches:
      - main
    paths: 
      - 'auth/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - run: cd auth && docker build -t rokufsd/auth .
      - run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - run: docker push rokufsd/auth
