name: deploy-auth
on:
  push:
    branches:
      - main
    paths: 
      - 'auth/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - run: cd auth && docker build -t rokufsd/auth .
      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - run: docker push rokufsd/auth
